### ISSUE TITLE
Spelling error in contributions page

### ISSUE THREAD

**Issue by nedjulius** [nyu-ossd-s20/mattfan00-weekly#1]
Hey Matthew,

I don't want to be an A.H., but I've noticed a spelling error in your contributions page. The image of the error is attached to this issue.

![screenshot2](https://user-images.githubusercontent.com/45975811/75381686-33cbd300-58a7-11ea-8d1f-66f863034968.png)

**Comment by mattfan00** [comment]
Hey Julius, I just saw this, thank you for point it out! Fixed it!
